# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/sidhantdabas3@gmail.com/NorthwindPipeline")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

customer_df = spark.read.table("northwind.bronze.customers")
display(customer_df)

# COMMAND ----------

from pyspark.sql.functions import from_json, col, explode, to_date
from pyspark.sql import functions as F
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, BooleanType, FloatType, DateType, ArrayType, DoubleType

# COMMAND ----------

customer_schema =  StructType([
    StructField("CustomerID", StringType(), False),
    StructField("CompanyName", StringType(), True),
    StructField("ContactName", StringType(), True),
    StructField("ContactTitle", StringType(), True),
    StructField("City", StringType(), True),
    StructField("Country", StringType(), True),
    StructField("Phone", StringType(), True)
                ])
customer_df = customer_df \
    .withColumn("parsed", from_json(col("raw_json"), customer_schema)) \
    .select("parsed.*", "_ingested_at")
display(customer_df)

# COMMAND ----------

products_df = spark.read.table("northwind.bronze.products")
display(products_df)

# COMMAND ----------

Products_schema =  StructType([
    StructField("ProductID", IntegerType(), False),
    StructField("ProductName", StringType(), True),
    StructField("QuantityPerUnit", StringType(), True),
    StructField("UnitPrice", FloatType(), True),
    StructField("UnitsInStock", IntegerType(), True),
    StructField("Discontinued", BooleanType(), True),
    StructField("CategoryName", StringType(), True),
    StructField("SupplierName", StringType(), True)
                ])
products_df = products_df \
    .withColumn("parsed", from_json(col("raw_json"), Products_schema)) \
    .select("parsed.*", "_ingested_at")
display(products_df)

# COMMAND ----------

orders_raw = spark.read.table("northwind.bronze.orders")
display(orders_raw)

# COMMAND ----------

line_item_schema = StructType([
    StructField("ProductID", IntegerType(), True),
    StructField("UnitPrice", FloatType(), True),
    StructField("Quantity", IntegerType(), True),
    StructField("Discount", FloatType(), True),
    StructField("LineTotal", FloatType(), True)
])
orders_schema =  StructType([
    StructField("OrderID", IntegerType(), False),
    StructField("CustomerID", StringType(), True),
    StructField("EmployeeID", IntegerType(), True),
    StructField("OrderDate", DateType(), True),
    StructField("ShippedDate", DateType(), True),
    StructField("Freight", FloatType(), True),
    StructField("ShipCity", StringType(), True),
    StructField("ShipCountry", StringType(), True),
    StructField("line_items", ArrayType(line_item_schema), True)
                ])

parsed_df = orders_raw \
    .withColumn("parsed", from_json(col("raw_json"), orders_schema)) \
    .select("parsed.*", "_ingested_at")

display(parsed_df)

# COMMAND ----------

orders_df = parsed_df \
    .drop("line_items") \
    .withColumn("OrderDate", to_date(col("OrderDate"))) \
    .withColumn("ShippedDate", to_date(col("ShippedDate"))) \
    .dropDuplicates(["OrderID"])

display(orders_df)

# Explode:
order_details = parsed_df \
    .select(
        col("OrderID"),
        col("CustomerID"),
        col("_ingested_at"),
        explode(col("line_items")).alias("item")
    ) \
    .select(
        col("OrderID"),
        col("CustomerID"),
        col("item.ProductID"),
        col("item.UnitPrice"),
        col("item.Quantity"),
        col("item.Discount"),
        col("item.LineTotal"),
        col("_ingested_at")
    )

display(order_details)

# COMMAND ----------

order_details.groupBy("OrderID").sum("LineTotal").orderBy("sum(LineTotal)", ascending=False).show()
order_details.groupBy("ProductID").sum("LineTotal").orderBy("sum(LineTotal)", ascending=False).show()
orders_combined = orders_df.join(order_details, "OrderID")

# COMMAND ----------

comparison = orders_combined.groupBy("ShipCity", "ShipCountry") \
                        .agg(F.sum("LineTotal").alias("total_revenue")) \
                        .orderBy("total_revenue", ascending=False)
comparison.show()

# COMMAND ----------

prod_order_details = order_details.join(products_df, "ProductID")
crm_master = orders_df.join(customer_df, "CustomerID") \
                   .join(prod_order_details, "OrderID")
crm_master.groupBy("ShipCity").avg("LineTotal").orderBy("avg(LineTotal)", ascending=False).show()

# COMMAND ----------

crm_master.groupBy("ShipCity").avg("LineTotal").orderBy("avg(LineTotal)", ascending=False).show()
